import Link from "next/link";

const sections = [
  {
    title: "1. Who We Are",
    paragraphs: [
      "Fidelity Traders Hub is operated by Fidelity Nasir Innovation Limited (CAC RC 8581474). This Privacy Policy explains how we collect, use, store, disclose and protect personal data when you visit our website, create an account, use our marketplace, wallet, Pay Small Small, Trade Journal, support or related services.",
      "Fidelity Traders Hub acts as an independent trading-services facilitator. We are not affiliated with Fidelity Investments.",
    ],
  },
  {
    title: "2. Personal Data We Collect",
    paragraphs: [
      "Depending on how you use the platform, we may collect the following categories of information:",
    ],
    items: [
      "Account and profile information, including your name, email address, telephone number, profile photograph and user role.",
      "Transaction information, including wallet activity, deposits, withdrawals, savings contributions, purchases, amounts, currency, status and delivery records.",
      "Bank-account information that you provide for an authorised withdrawal.",
      "Product and fulfilment information, including selected products, account sizes, purchase links, registered portal email and portal password where you ask us to complete an external purchase on your behalf.",
      "Trade Journal information, including trading accounts, risk plans, systems, trade records, notes, results, emotions, mistakes, lessons and chart screenshots.",
      "Support messages, requests, announcements viewed and other communications with our team.",
      "Technical information such as device, browser, IP address, session, authentication and security logs where generated by our platform or service providers.",
    ],
  },
  {
    title: "3. Sensitive Credentials",
    paragraphs: [
      "If an external product requires us to purchase or register through a third-party portal, we may ask for the portal email and portal password needed for that specific fulfilment request. You must never provide your Gmail, Yahoo, banking, payment-card or other unrelated personal password.",
      "We use submitted portal credentials only to process the authorised request, provide delivery or support and maintain necessary transaction records. You should change any temporary portal password after fulfilment where the provider permits it.",
    ],
  },
  {
    title: "4. How We Use Personal Data",
    items: [
      "Create, authenticate and secure your account.",
      "Process purchases, wallet activity, savings plans, withdrawals and product delivery.",
      "Provide Trade Journal storage, calculations, analytics and screenshots.",
      "Verify transactions, prevent fraud, investigate misuse and enforce our terms.",
      "Provide customer support and communicate service or request updates.",
      "Maintain records required for accounting, dispute handling, legal compliance and platform administration.",
      "Improve platform reliability, accessibility, performance and user experience.",
    ],
  },
  {
    title: "5. Lawful Bases",
    paragraphs: [
      "We process personal data where it is necessary to perform a contract with you, comply with a legal obligation, pursue a legitimate business or security interest, protect vital interests, or where you have given consent. Where processing is based on consent, you may withdraw that consent, although this does not affect processing already carried out lawfully.",
    ],
  },
  {
    title: "6. When We Share Information",
    paragraphs: [
      "We do not sell personal data. We may share only the information reasonably necessary with:",
    ],
    items: [
      "Hosting, database, authentication, storage, analytics, communications and other technology providers that support the platform.",
      "Payment, banking or transaction-service providers involved in deposits, withdrawals or purchase processing.",
      "A prop firm, software provider or other product provider when needed to complete a request you authorised.",
      "Professional advisers, regulators, law-enforcement bodies or courts where disclosure is required or legally justified.",
      "A successor organisation in connection with a lawful merger, restructuring or transfer of the business, subject to appropriate safeguards.",
    ],
  },
  {
    title: "7. Data Retention",
    paragraphs: [
      "We retain personal data only for as long as reasonably necessary for the purpose for which it was collected, including account operation, fulfilment, support, security, dispute resolution, accounting and legal obligations. Retention periods may differ by record type. Data may be deleted, anonymised or securely restricted when it is no longer required.",
    ],
  },
  {
    title: "8. Security",
    paragraphs: [
      "We use reasonable administrative, technical and organisational safeguards designed to protect personal data against unauthorised access, alteration, disclosure, loss or destruction. No internet service is completely risk-free, so users must also protect their login details, use strong unique passwords and notify support promptly about suspected unauthorised access.",
    ],
  },
  {
    title: "9. Your Privacy Rights",
    paragraphs: [
      "Subject to applicable law and any valid exemptions, you may request access to your personal data, correction of inaccurate data, deletion, restriction, objection to certain processing, data portability, or withdrawal of consent. You may also complain to the Nigeria Data Protection Commission where you believe your data-protection rights have been infringed.",
      "To make a privacy request, contact Fidelity Traders Hub through the support channel shown on the website or your dashboard. We may need to verify your identity before acting on the request.",
    ],
  },
  {
    title: "10. Cookies and Local Storage",
    paragraphs: [
      "The platform may use essential cookies, browser storage and similar technologies to keep you signed in, remember your selected theme, protect sessions and operate core features. Where non-essential analytics or marketing technologies are introduced, we will provide any notice or choice required by applicable law.",
    ],
  },
  {
    title: "11. International Processing",
    paragraphs: [
      "Some technology or product providers may process information outside Nigeria. Where an international transfer occurs, we take reasonable steps to use providers and safeguards consistent with applicable data-protection requirements.",
    ],
  },
  {
    title: "12. Children",
    paragraphs: [
      "Fidelity Traders Hub is not intended for children under 18. We do not knowingly request that a child create a trading-services account. If we learn that personal data was collected from a child without appropriate authority, we will take reasonable steps to remove it.",
    ],
  },
  {
    title: "13. Third-Party Services",
    paragraphs: [
      "Our website may link to prop firms, TradingView or other independent services. Their privacy practices are governed by their own policies. You should review those policies before submitting information directly to a third party.",
    ],
  },
  {
    title: "14. Changes to This Policy",
    paragraphs: [
      "We may update this Privacy Policy when our services, technology or legal obligations change. The revised version will be published on this page with an updated effective date. Material changes may also be communicated through the platform where appropriate.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[var(--background)] px-5 py-10 text-[var(--foreground)] sm:px-6 sm:py-12">
      <div className="mx-auto max-w-4xl">
        <Link
          href="/"
          className="text-sm font-bold text-[var(--brand-primary)] hover:underline"
        >
          ← Back to Fidelity Traders Hub
        </Link>

        <header className="mt-8 rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-sm)] sm:p-8">
          <p className="text-sm font-black uppercase tracking-[0.16em] text-[var(--brand-primary)]">
            Legal &amp; Privacy
          </p>
          <h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 max-w-2xl leading-7 text-[var(--muted)]">
            This policy explains how Fidelity Traders Hub handles personal data and the choices available to you.
          </p>
          <p className="mt-4 text-sm font-semibold text-[var(--muted)]">
            Effective date: 29 August 2026
          </p>
        </header>

        <section className="mt-8 rounded-2xl border border-[var(--brand-primary)]/25 bg-[var(--brand-soft)] p-5 sm:p-6">
          <h2 className="text-xl font-black text-[var(--brand-primary)]">
            Our privacy commitment
          </h2>
          <p className="mt-3 leading-7 text-[var(--foreground)]">
            We aim to process personal data lawfully, fairly and transparently; collect only what is relevant; keep records accurate; retain them only as necessary; and apply appropriate security. This policy is designed with the Nigeria Data Protection Act 2023 in mind.
          </p>
        </section>

        <div className="mt-8 space-y-5">
          {sections.map((section) => (
            <section
              key={section.title}
              className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--shadow-sm)] sm:p-7"
            >
              <h2 className="text-xl font-black">{section.title}</h2>

              {section.paragraphs?.map((paragraph) => (
                <p key={paragraph} className="mt-3 leading-7 text-[var(--muted)]">
                  {paragraph}
                </p>
              ))}

              {section.items && (
                <ul className="mt-4 list-disc space-y-2 pl-6 leading-7 text-[var(--muted)]">
                  {section.items.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>

        <section className="mt-8 rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-6 text-center">
          <h2 className="text-xl font-black">Privacy questions or requests?</h2>
          <p className="mx-auto mt-3 max-w-2xl leading-7 text-[var(--muted)]">
            Contact Fidelity Traders Hub using the support option on the website or from your signed-in dashboard.
          </p>
          <Link
            href="/dashboard"
            className="mt-5 inline-flex rounded-xl bg-[var(--brand-primary)] px-5 py-3 font-black text-white"
          >
            Open Dashboard Support
          </Link>
        </section>
      </div>
    </main>
  );
}
